using System;

namespace FINT.Model.Ressurs.Datautstyr
{
	public enum DatautstyrActions
    {
	
	GET_ENHETSGRUPPEMEDLEMSKAP,
	GET_ALL_ENHETSGRUPPEMEDLEMSKAP,
	UPDATE_ENHETSGRUPPEMEDLEMSKAP,
	GET_ENHETSGRUPPE,
	GET_ALL_ENHETSGRUPPE,
	UPDATE_ENHETSGRUPPE,
	GET_DIGITALENHET,
	GET_ALL_DIGITALENHET,
	UPDATE_DIGITALENHET
    }
}
