using System;

namespace FINT.Model.Arkiv.Noark
{
	public enum NoarkActions
    {
	
	GET_TILGANG,
	GET_ALL_TILGANG,
	UPDATE_TILGANG,
	GET_SAK,
	GET_ALL_SAK,
	UPDATE_SAK,
	GET_KLASSIFIKASJONSSYSTEM,
	GET_ALL_KLASSIFIKASJONSSYSTEM,
	UPDATE_KLASSIFIKASJONSSYSTEM,
	GET_DOKUMENTFIL,
	GET_ALL_DOKUMENTFIL,
	UPDATE_DOKUMENTFIL,
	GET_AUTORISASJON,
	GET_ALL_AUTORISASJON,
	UPDATE_AUTORISASJON,
	GET_ARKIVRESSURS,
	GET_ALL_ARKIVRESSURS,
	UPDATE_ARKIVRESSURS,
	GET_ARKIVDEL,
	GET_ALL_ARKIVDEL,
	UPDATE_ARKIVDEL,
	GET_ADMINISTRATIVENHET,
	GET_ALL_ADMINISTRATIVENHET,
	UPDATE_ADMINISTRATIVENHET
    }
}
